name: "OPDS"
guid: "F30880AE-3365-449E-B9E6-BF133C8401B0"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-opds.png"
version: "3"
targetAbi: "10.7.7.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Provides an OPDS book feed"
description: >
  Provides an OPDS feed for book browsing.

category: "General"
artifacts:
  - "Jellyfin.Plugin.Opds.dll"
changelog: |2-
  ### New features and improvements ###
  - Add Genre search (#9) @crobibero
  - Use Request.PathBase to get actual baseUrl (#8) @crobibero

  ### Code or Repo Maintenance ###
  - Use BaseItemKind (#10) @crobibero
  - Update ruleset, fix build, fix ordering (#3) @crobibero
