name: "OPDS"
guid: "F30880AE-3365-449E-B9E6-BF133C8401B0"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-opds.png"
version: "2"
targetAbi: "10.8.0.0"
framework: "net6.0"
owner: "jellyfin"
overview: "Provides an OPDS book feed"
description: >
  Provides an OPDS feed for book browsing.

category: "General"
artifacts:
  - "Jellyfin.Plugin.Opds.dll"
changelog: |2-
  ### Code or Repo Maintenance ###
  - 10.8 support (#1) @crobibero
